// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxqXS7dy2GyxdMF_zn4OXaE-QpgeqGHE',
    appId: '1:1066433983088:web:4d262011ea2906e818bab5',
    messagingSenderId: '1066433983088',
    projectId: 'queue-22747',
    authDomain: 'queue-22747.firebaseapp.com',
    storageBucket: 'queue-22747.appspot.com',
    measurementId: 'G-MF4NW53MR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQi3Dcz2LTCmIqbou0HP2wldhjXkXSE4',
    appId: '1:1066433983088:android:1f7b90336de7915018bab5',
    messagingSenderId: '1066433983088',
    projectId: 'queue-22747',
    storageBucket: 'queue-22747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXXZD2qOPDFayJnxtwxbPJdpe8cUT33j4',
    appId: '1:1066433983088:ios:7bccd9a3e96ba65d18bab5',
    messagingSenderId: '1066433983088',
    projectId: 'queue-22747',
    storageBucket: 'queue-22747.appspot.com',
    iosClientId:
        '1066433983088-69pk8kbnpgci0071ede97i5rs5qhk3lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.queue',
  );
}
