name: queue
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^9.0.3
  spotify_sdk: ^2.3.1
  workmanager: ^0.5.1
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  fake_cloud_firestore: ^2.4.1+1
  get_it: ^7.6.0
  mockito: ^5.4.2
  firebase_auth: ^4.7.1
  firebase_auth_mocks: ^0.12.0
  google_sign_in_mocks: ^0.3.0
  firebase_ui_auth: ^1.6.1
  firebase_ui_oauth_google: ^1.2.6
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  http: ^1.1.0
  equatable: ^2.0.5
  collection: ^1.17.1
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
